# Generated by Django 5.0.3 on 2024-03-22 10:41

import the_pass.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.ImageField(null=True, upload_to=the_pass.services.get_path_upload_photo),
        ),
    ]
